config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'copy_succeed', to: 'pages#copy_succeed'
  get 'copy_wenbo', to: 'pages#copy_wenbo'
  get 'baidu', to: 'pages#baidu'
  get 'zhihu', to: 'pages#zhihu'
  get '51upali', to: 'pages#upali'

  resources :virtual_orders
  resources :page_visitors
  mount Split::Dashboard, at: 'split'
  get 'pages/contact'
  get 'pages/company'
  get 'pages/products'
  get '/dashboard', to: 'pages#dashboard'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'pages#home'
end

app/models/virtual_order.rb
class VirtualOrder < ApplicationRecord
end

app/controllers/virtual_orders_controller.rb
class VirtualOrdersController < ApplicationController
  before_action :set_virtual_order, only: [:show, :edit, :update, :destroy]

  # GET /virtual_orders
  # GET /virtual_orders.json
  def index
    @virtual_orders = VirtualOrder.all
  end

  # GET /virtual_orders/1
  # GET /virtual_orders/1.json
  def show
  end

  # GET /virtual_orders/new
  def new
    @virtual_order = VirtualOrder.new
  end

  # GET /virtual_orders/1/edit
  def edit
  end

  # POST /virtual_orders
  # POST /virtual_orders.json
  def create
    @virtual_order = VirtualOrder.new(virtual_order_params)

    respond_to do |format|
      if @virtual_order.save
        format.html { redirect_to @virtual_order, notice: 'Virtual order was successfully created.' }
        format.json { render :show, status: :created, location: @virtual_order }
      else
        format.html { render :new }
        format.json { render json: @virtual_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /virtual_orders/1
  # PATCH/PUT /virtual_orders/1.json
  def update
    respond_to do |format|
      if @virtual_order.update(virtual_order_params)
        format.html { redirect_to @virtual_order, notice: 'Virtual order was successfully updated.' }
        format.json { render :show, status: :ok, location: @virtual_order }
      else
        format.html { render :edit }
        format.json { render json: @virtual_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /virtual_orders/1
  # DELETE /virtual_orders/1.json
  def destroy
    @virtual_order.destroy
    respond_to do |format|
      format.html { redirect_to virtual_orders_url, notice: 'Virtual order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_virtual_order
      @virtual_order = VirtualOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def virtual_order_params
      params.require(:virtual_order).permit(:name, :phone, :address, :product_count, :payment)
    end
end

app/helpers/virtual_orders_helper.rb
module VirtualOrdersHelper
end

app/views/virtual_orders/_form.html.erb
<%= form_for(virtual_order) do |f| %>
  <% if virtual_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(virtual_order.errors.count, "error") %> prohibited this virtual_order from being saved:</h2>

      <ul>
      <% virtual_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "客户姓名" %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label "联系方式" %>
    <%= f.text_field :phone %>
  </div>

  <div class="form-group">
    <%= f.label "订购数量" %>
    <%= f.text_field :product_count %>
  </div>

  <div class="form-group">
    <%= f.label "付款方式" %>
    <%= f.text_field :payment %>
  </div>

  <div class="form-group">
    <%= f.label "发货地址" %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit "立即抢购", class: "btn btn-default" %>
  </div>
    <br>
<% end %>

app/views/virtual_orders/edit.html.erb
<h1>Editing Virtual Order</h1>

<%= render 'form', virtual_order: @virtual_order %>

<%= link_to 'Show', @virtual_order %> |
<%= link_to 'Back', virtual_orders_path %>

app/views/virtual_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Virtual Orders</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Product count</th>
      <th>Payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @virtual_orders.each do |virtual_order| %>
      <tr>
        <td><%= virtual_order.name %></td>
        <td><%= virtual_order.phone %></td>
        <td><%= virtual_order.address %></td>
        <td><%= virtual_order.product_count %></td>
        <td><%= virtual_order.payment %></td>
        <td><%= link_to 'Show', virtual_order %></td>
        <td><%= link_to 'Edit', edit_virtual_order_path(virtual_order) %></td>
        <td><%= link_to 'Destroy', virtual_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Virtual Order', new_virtual_order_path %>

app/views/virtual_orders/new.html.erb
<h1>New Virtual Order</h1>

<%= render 'form', virtual_order: @virtual_order %>

<%= link_to 'Back', virtual_orders_path %>

app/views/virtual_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @virtual_order.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @virtual_order.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @virtual_order.address %>
</p>

<p>
  <strong>Product count:</strong>
  <%= @virtual_order.product_count %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @virtual_order.payment %>
</p>

<%= link_to 'Edit', edit_virtual_order_path(@virtual_order) %> |
<%= link_to 'Back', virtual_orders_path %>