config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'copy_succeed', to: 'pages#copy_succeed'
  get 'copy_wenbo', to: 'pages#copy_wenbo'
  get 'baidu', to: 'pages#baidu'
  get 'zhihu', to: 'pages#zhihu'
  get '51upali', to: 'pages#upali'

  resources :virtual_orders
  resources :page_visitors
  mount Split::Dashboard, at: 'split'
  get 'pages/contact'
  get 'pages/company'
  get 'pages/products'
  get '/dashboard', to: 'pages#dashboard'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'pages#home'
end

app/models/page_visitor.rb
class PageVisitor < ApplicationRecord
end

app/controllers/page_visitors_controller.rb
class PageVisitorsController < ApplicationController
  before_action :set_page_visitor, only: [:show, :edit, :update, :destroy]

  # GET /page_visitors
  # GET /page_visitors.json
  def index
    # @page_visitors = PageVisitor.all.reverse.page params[:page]
    @page_visitors = PageVisitor.order(created_at: :desc).page params[:page]
  end

  # GET /page_visitors/1
  # GET /page_visitors/1.json
  def show
  end

  # GET /page_visitors/new
  def new
    @page_visitor = PageVisitor.new
  end

  # GET /page_visitors/1/edit
  def edit
  end

  # POST /page_visitors
  # POST /page_visitors.json
  def create
    @page_visitor = PageVisitor.new(page_visitor_params)

    respond_to do |format|
      if @page_visitor.save
        format.html { redirect_to @page_visitor, notice: 'Page visitor was successfully created.' }
        format.json { render :show, status: :created, location: @page_visitor }
      else
        format.html { render :new }
        format.json { render json: @page_visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_visitors/1
  # PATCH/PUT /page_visitors/1.json
  def update
    respond_to do |format|
      if @page_visitor.update(page_visitor_params)
        format.html { redirect_to @page_visitor, notice: 'Page visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_visitor }
      else
        format.html { render :edit }
        format.json { render json: @page_visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_visitors/1
  # DELETE /page_visitors/1.json
  def destroy
    @page_visitor.destroy
    respond_to do |format|
      format.html { redirect_to page_visitors_url, notice: 'Page visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_visitor
      @page_visitor = PageVisitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_visitor_params
      params.require(:page_visitor).permit(:RemoteIP, :Page, :Referer, :UserAgent, :page)
    end
end

app/helpers/page_visitors_helper.rb
module PageVisitorsHelper
  def device (agent)
    case agent
      # mobile
      when /Android/i && /OPPO/i
        return 'OPPO'
      when /Android/i && /HUAWEI/i
        return 'HUAWEI'
      when /Android/i && /vivo/i
        return 'vivo'
      when /Android/i && /Xiaomi/i
        return 'Xiaomi'
      when /Android/i && /Lenovo/i
        return 'Lenovo'
      when /Android/i
        return 'Android'
      when /iPhone/i
        return 'iPhone'
      when /iPad/i
        return 'iPad'
      # pc
      when /Macintosh/i
        return 'Mac'
      when /Windows/i
        return 'Windows'
      when nil
        return '空'
      else
        return '未判断'
    end
  end

  def source (referer)
    case referer
      when /baidu/i
        if referer =~ /word/
          keyword = referer.sub(/^.*word=/, "")
          keyword = URI.unescape keyword.sub(/&.*$/, "")
          return "百度, 关键词:#{keyword}"
        else
          return "百度, 关键词: 空"
        end
        # get the keyword
      when nil
        return '空'
      else
        return '不可判断来源'
    end
  end
end

app/views/page_visitors/_form.html.erb
<%= form_for(page_visitor) do |f| %>
  <% if page_visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page_visitor.errors.count, "error") %> prohibited this page_visitor from being saved:</h2>

      <ul>
      <% page_visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :RemoteIP %>
    <%= f.text_field :RemoteIP %>
  </div>

  <div class="field">
    <%= f.label :Page %>
    <%= f.text_field :Page %>
  </div>

  <div class="field">
    <%= f.label :Referer %>
    <%= f.text_field :Referer %>
  </div>

  <div class="field">
    <%= f.label :UserAgent %>
    <%= f.text_field :UserAgent %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/page_visitors/edit.html.erb
<h1>Editing Page Visitor</h1>

<%= render 'form', page_visitor: @page_visitor %>

<%= link_to 'Show', @page_visitor %> |
<%= link_to 'Back', page_visitors_path %>

app/views/page_visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Page Visitors</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>日期</th>
      <th>时间</th>
      <th>IP</th>
      <th>页面</th>
      <th>来源</th>
      <th>设备</th>
      <!--<th colspan="3">操作</th>-->
    </tr>
  </thead>

  <tbody>
    <% @page_visitors.each do |page_visitor| %>
      <tr>
        <td><%= page_visitor.updated_at.strftime("%Y-%m-%d") %></td>
        <td><%= page_visitor.updated_at.strftime("%H:%M:%S") %></td>
        <td><%= page_visitor.RemoteIP %></td>
        <td><%= page_visitor.Page %></td>
        <td><%=  source page_visitor.Referer %></td>
        <td><%= device page_visitor.UserAgent %></td>
        <td><%= link_to 'Show', page_visitor %></td>
        <!--<td><%= link_to 'Edit', edit_page_visitor_path(page_visitor) %></td>-->
        <!--<td><%= link_to 'Destroy', page_visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @page_visitors %>

<br>

app/views/page_visitors/new.html.erb
<h1>New Page Visitor</h1>

<%= render 'form', page_visitor: @page_visitor %>

<%= link_to 'Back', page_visitors_path %>

app/views/page_visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Remoteip:</strong>
  <%= @page_visitor.RemoteIP %>
</p>

<p>
  <strong>Page:</strong>
  <%= @page_visitor.Page %>
</p>

<p>
  <strong>Referer:</strong>
  <%= @page_visitor.Referer %>
</p>

<p>
  <strong>设备:</strong>
  <%= @page_visitor.UserAgent %>
</p>

<p>
  <strong>时间:</strong>
  <%= @page_visitor.created_at %>
</p>

<%= link_to 'Edit', edit_page_visitor_path(@page_visitor) %> |
<%= link_to 'Back', page_visitors_path %>