config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'copy_succeed', to: 'pages#copy_succeed'
  get 'copy_wenbo', to: 'pages#copy_wenbo'
  get 'baidu', to: 'pages#baidu'
  get 'zhihu', to: 'pages#zhihu'
  get '51upali', to: 'pages#upali'

  resources :virtual_orders
  resources :page_visitors
  mount Split::Dashboard, at: 'split'
  get 'pages/contact'
  get 'pages/company'
  get 'pages/products'
  get '/dashboard', to: 'pages#dashboard'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'pages#home'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <% unless key == :timedout %>
    <%= content_tag :div, class: "alert alert-dismissable alert-#{key}" do -%>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= msg %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<p class="text-muted">
  &copy; <%= Time.now.year.to_s %> Orats - All rights reserved
</p>

app/views/layouts/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_UA'].present? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  // Enable 'Demographics and interest reports' in your analytics settings
  // ga('require', 'displayfeatures');

  // Enable 'Use enhanced link attribution' in your analytics settings
  // ga('require', 'linkid', 'linkid.js');

  ga('create', '<%= ENV["GOOGLE_ANALYTICS_UA"] %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '优波粒', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li><%= link_to '流量', page_visitors_path %></li>
        <li><%= link_to '虚拟订单', virtual_orders_path %></li>
        <li><%= link_to 'ab测试', '/split' %></li>
        <li><%= link_to '首页', root_path %></li>
        <li><%= link_to '退出', logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="zh-CN">
<head>
  <title><%= yield :title %></title>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= yield :meta_description %>"/>

  <%#= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
  <script
      src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <script
      src="//cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
  <script
      src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
  <![endif]-->
</head>

<body>
  <%= render 'layouts/google_analytics' %>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <main role="main" class="container">
    <div class="page-header">
      <h1><%= yield :heading %></h1>
    </div>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </main>

  <footer>
    <hr/>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </footer>
</body>
</html>

app/views/layouts/baidu_layout.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>隆回县顺道电子商务有限公司</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link href="/css/flexslider.min.css" rel="stylesheet" type="text/css" media="all"/>
  <link href="/css/line-icons.min.css" rel="stylesheet" type="text/css" media="all"/>
  <link href="/css/elegant-icons.min.css" rel="stylesheet" type="text/css" media="all"/>
  <link href="/css/lightbox.min.css" rel="stylesheet" type="text/css" media="all"/>
  <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all"/>
  <link href="/css/theme.css" rel="stylesheet" type="text/css" media="all"/>
  <link href="/css/custom.css" rel="stylesheet" type="text/css" media="all"/>
  <!--[if gte IE 9]>
    <link rel="stylesheet" type="text/css" href="/css/ie9.css" />
<![endif]-->
  <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700%7CRaleway:700' rel='stylesheet' type='text/css'>-->
  <script src="/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
  <script>
      var _hmt = _hmt || [];
      (function() {
          var hm = document.createElement("script");
          hm.src = "https://hm.baidu.com/hm.js?119ff8c734f5a52ef0854098b017bdbb";
          var s = document.getElementsByTagName("script")[0];
          s.parentNode.insertBefore(hm, s);
      })();
  </script>

</head>
<body>
<div class="loader">
  <div class="spinner">
    <div class="double-bounce1"></div>
    <div class="double-bounce2"></div>
  </div>
</div>

<div class="nav-container">
  <nav class="top-bar overlay-bar">
    <div class="container">

      <div class="row utility-menu">
        <div class="col-sm-12">
          <div class="utility-inner clearfix">
            <span class="alt-font"><i class="icon icon_pin"></i> 0731-89908814</span>
            <span class="alt-font"><i class="icon icon_mail"></i>联系人：罗先生</span>
          </div>
        </div>
      </div><!--end of row-->


      <div class="row nav-menu">
        <div class="col-sm-5 col-md-4 columns">
          <%= link_to  root_path do %>
          <h2 class="logo logo-light" style="color: white">隆回县顺道电子商务有限公司</h2>
          <h2 class="logo logo-dark">隆回县顺道电子商务有限公司</h2>
          <% end %>
        </div>

        <div class="col-sm-7 col-md-8 columns">
          <ul class="menu">
            <li><%= link_to '首页', root_path %></li>
            <li><%= link_to '产品介绍', pages_products_path, {:onclick=>"_hmt.push(['_trackEvent', 'nav', 'click',
            'product'])"} %></li>
            <li><%= link_to '公司简介', pages_company_path %></li>
            <li><%= link_to '联系我们', pages_contact_path %></li>
          </ul>

        </div>
      </div><!--end of row-->

      <div class="mobile-toggle">
        <i class="icon icon_menu"></i>
      </div>

    </div><!--end of container-->
  </nav>
</div>
<div class="main-container">
  <%= yield %>
</div>
<div class="footer-container">
  <footer class="bg-primary short-2">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <span class="text-white">© 2017- 隆回县顺道电子商务有限公司.</span>
          <span class="text-white">联系人：罗先生</span>
          <span class="text-white">0731-89908814</span>
          <span class="text-white">湖南省邵阳市隆回县桃洪镇桃洪西路（怡然花园内）</span>
        </div>
      </div><!--end for row-->
    </div><!--end of container-->

    <div class="contact-action">
      <div class="align-vertical">
        <i class="icon text-white icon_mail"></i>
        <%= link_to pages_contact_path, class: "text-white" do %>
        <span class="text-white">联系我们<i class="icon arrow_right"></i></span>
        <% end %>
      </div>
    </div>
  </footer>
</div>

<style>
  #newBridge{
    display: none!important;
  }
</style>

<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.plugin.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.flexslider-min.js"></script>
<script src="/js/smooth-scroll.min.js"></script>
<script src="/js/skrollr.min.js"></script>
<script src="/js/spectragram.min.js"></script>
<script src="/js/scrollReveal.min.js"></script>
<script src="/js/isotope.min.js"></script>
<!--<script src="js/twitterFetcher_v10_min.js"></script>-->
<script src="/js/lightbox.min.js"></script>
<script src="/js/jquery.countdown.min.js"></script>
<script src="/js/scripts.js"></script>
</body>
</html>